name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 11
          - 17
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
      # Lovingly stolen from: https://github.com/bluefireteam/audioplayers/blob/main/.github/workflows/test.yml
      - name: Start audio server
        run: net start audiosrv
      - name: List Audio Devices
        run: Get-CimInstance Win32_SoundDevice | fl *
      - name: Disable time sync with Hyper-V & setting system date time (#1573)
        # Remove workaround of setting the time when virtual audio device certificate is valid again (#1573)
        run: |
          Set-Service -Name vmictimesync -Status stopped -StartupType disabled
          Set-ItemProperty HKLM:\SYSTEM\CurrentControlSet\services\W32Time\Parameters -Name 'Type' -Value 'NoSync'
          net stop w32time; Set-Date (Get-Date "2023-07-04 12:00:00")
      - name: Install Scream
        shell: powershell
        run: |
          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/4.0/Scream4.0.zip -OutFile Scream.zip
          Expand-Archive -Path Scream.zip -DestinationPath Scream
          Import-Certificate -FilePath Scream\Install\driver\x64\Scream.cat -CertStoreLocation Cert:\LocalMachine\TrustedPublisher
          Scream\Install\helpers\devcon-x64.exe install Scream\Install\driver\x64\Scream.inf *Scream
      - name: Resetting system date time (#1573)
        run: |
          Set-Service -Name vmictimesync -Status running -StartupType automatic
          Set-ItemProperty HKLM:\SYSTEM\CurrentControlSet\services\W32Time\Parameters -Name 'Type' -Value 'NTP'
          net start w32time; w32tm /resync /force; $currentDate = Get-Date; Write-Host "Current System Date: $currentDate";
      - name: List Audio Devices
        run: Get-CimInstance Win32_SoundDevice | fl *
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
  macos:
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 11
          - 17
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
# Disabling for now as I need to figure out how to get a virtual audio card working
#  ubuntu:
#    strategy:
#      fail-fast: false
#      matrix:
#        os:
#          - ubuntu-latest
#        java-version:
#          - 11
#          - 17
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: Install GStreamer
#        # Install libunwind-dev, see https://github.com/actions/runner-images/issues/6399#issuecomment-1285011525
#        run: |
#          sudo apt-get update
#          sudo apt install -y libunwind-dev
#          sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good gstreamer1.0-plugins-bad
#      - name: Setup JDK ${{ matrix.java-version }}
#        uses: actions/setup-java@v3
#        with:
#          java-version: ${{ matrix.java-version }}
#          distribution: "temurin"
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#      - name: Build
#        run : |
#          export DISPLAY=:99
#          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
#          ./gradlew build --info
