name: CI(windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 11
          - 17
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
      - name: List Audio Devices
        run: Get-CimInstance Win32_SoundDevice | fl *
      - name: Install Scream
        shell: powershell
        run: |
          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/4.0/Scream4.0.zip -OutFile Scream.zip
          Expand-Archive -Path Scream.zip -DestinationPath Scream
          Import-Certificate -FilePath Scream\Install\driver\x64\Scream.cat -CertStoreLocation Cert:\LocalMachine\TrustedPublisher
          Scream\Install\helpers\devcon-x64.exe install Scream\Install\driver\x64\Scream.inf *Scream
      - name: List Audio Devices
        run: Get-CimInstance Win32_SoundDevice | fl *
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
