name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 11
          - 17
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
      - name: List Audio Devices
        run: Get-CimInstance Win32_SoundDevice | fl *
      - name: Install Scream
        shell: powershell
        run: |
          Start-Service audio*
          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.9/Scream3.9.zip -OutFile C:\Scream3.9.zip
          Extract-7Zip -Path C:\Scream3.9.zip -DestinationPath C:\Scream
          $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
          $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
          $store.Open("ReadWrite")
          $store.Add($cert)
          $store.Close()
          cd C:\Scream\Install\driver
          C:\Scream\Install\helpers\devcon-x64 install Scream.inf *Scream
      - name: List Audio Devices
        run: Get-CimInstance Win32_SoundDevice | fl *
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
